DELIMITER $$
CREATE PROCEDURE `proc_getSalaryDocumentData`(
	IN `documentID` INTEGER
)
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN    
	SELECT * FROM salary where docID = documentID;
END$$
DELIMITER ;
